on: push

jobs:
  test:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Choco help
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install -y notepadplusplus
      -
        name: Find N++
        shell: cmd
        run: |
          where notepad++.exe
          dir /N/S C:\ProgramData\Chocolatey\bin\
