on: push

jobs:
  test:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Choco help
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          #args: install -y notepadplusplus.commandline
          args: install -y notepadplusplus
      -
        name: Find N++
        shell: cmd
        run: |
          dir /N/S "C:\Program Files\Notepad++\"
          dir /N/S "%AppData%\Notepad++\"

